### ISSUE TITLE
Where to find the depth values gt and the moving object masks?

### ISSUE THREAD

**Issue by ameyskulkarni** [better-flow/evimo#1]
Hello @ncos @fluffyfunnypants @apozharski 
Thanks a lot for this great dataset. I checked the dataset but I was confused about where to find the depth image ground truth of the whole scene and the moving object masks? I believe the depth masks in the Text.txt files are the moving object masks as I don't see the ground truth depths of the background in that. It would be great if you could guide me to get the 

1. Whole image depth ground truth values
2. Moving object masks

Thanks

**Comment by ncos** [comment]
If you are using the .npz format, the masks are in 'mask' variable, and depth are in 'depth'; for now, we temporarily removed the background depth, but the depth for moving objects is still available (the rest of the values are set to 0).

In the .txt format, the masks and depth are in the img folder: these are 3-channel images; depth is the middle channel ([1]) and mask is in channel [2]; also see [line 262](https://github.com/better-flow/evimo/blob/master/evimo/dataset_frame.h).

Again, the background depth is not available (although you can run the generation pipeline on the raw data), but I will try to release it as soon as possible.
