### ISSUE TITLE
How to get the object's pose (R & t) in camera's coordinate?

### ISSUE THREAD

**Issue by AlanJiang98** [better-flow/evimo#12]
I want to get the **object's pose (R & t) in camera's coordinate system**. In the meta.txt file, I use the object's **'pos'** data as below.

`'1': {
	'pos': {'t': {'x': 0.202513, 'y': -0.107724, 'z': -0.482944}, 'rpy': {'r': 0.570423, 'p': 0.118242, 'y': 1.521588}, 'q': {'w': 0.705277, 'x': 0.164336, 'y': 0.234725, 'z': 0.648445}},
	'ts': 0.128009},
'gt_frame': 'depth_mask_4.png',
'classical_frame': 'img_4.png'`

When I render the mesh of the object to the camera plane with the object's pose, there is always a shift(20-50 pixels)  between the GT mask and the rendered mask. Am I missing some Information?

Thanks for your help!

**Comment by ncos** [comment]
In short, please look at (and try to reuse) [this](https://github.com/better-flow/evimo/blob/b2cff3cbe233e8f4c7a955450904fe538bd9c54e/tools/object_viewer.py#L75)

If you can provide a small code sample I could take a look. But likely:
1) Just to check: object poses we provide are in camera frame (not world); see [here](https://github.com/better-flow/evimo/blob/b2cff3cbe233e8f4c7a955450904fe538bd9c54e/evimo/dataset_frame.h#L286)

2) The problem might be that our 3D scans are provided as-is, in the coordinate frame that is not anyhow related to the mocap system (the scanning happened as a separate step). See [here](https://github.com/better-flow/evimo/wiki/Adding-a-New-Object): you will need to use the `config.txt ` to extract 3D locations of Vicon markers in *scanner frame* and warp these to a *vicon coordinate frame* (the trajectory of which we provide). Internally (in C++) we do this [here](https://github.com/better-flow/evimo/blob/b2cff3cbe233e8f4c7a955450904fe538bd9c54e/evimo/object.h#L393): we take vicon marker coordinates in world space, put them in a local space (using the vicon pose - which is a bit of a hack), and use SVD to move the entire pointcloud to the vicon frame.

You will likely need to reproduce this logic in your pipeline, which should be not too difficult! Use [these files](https://github.com/better-flow/evimo/blob/b2cff3cbe233e8f4c7a955450904fe538bd9c54e/evimo/objects/car_01/vicon.vsk#L1) to get vicon coordinate frame parameters, and take a look [here](https://github.com/better-flow/evimo/blob/b2cff3cbe233e8f4c7a955450904fe538bd9c54e/tools/object_viewer.py#L75) - this code already has the functionality you are looking for (please adapt for your use-case, and remove hardcoded matrices and such, the code is experimental)


Please let me know how this goes, and if you have a nice script you can make an MR to the 'tools' dir (and even add a wiki entry)!
