### ISSUE TITLE
how to synchronize the mask with the event and the frame image

### ISSUE THREAD

**Issue by adosum** [better-flow/evimo#13]
When I check the npz file and raw bag file. I found that the number of the masks and the frame image is different. And I also cannot group the event according to the number of masks.  Is there any recommended method to solve this problem? Thank you very much for the reply.

**Comment by ncos** [comment]
Sorry for the late reply; all data (including masks) comes with timestamps, and (naturally) events and images too; so that could be used to sync the data.

**Comment by adosum** [comment]
Yes, thank you very much for the reply. I made a mistake and that is why I closed this issue. I didn't check the text files before which have the sync raw_image and mask data. Now I have found them. 
Thank you very much again for the dataset and the reply.

**Comment by doublemanyu** [comment]
> ll data (including masks) comes with timestamps,

Hi，I have a question when I saw your reply. How did you get the timestamps of mask? Looking forward to your reply.

**Comment by aftersomemath** [comment]
In EVIMO2v2 the timestamps of the generated data (segmentation and depth masks) can be found in the `meta` field of `dataset_info.npz`. 

More information and examples of the contents of `meta` are provided on this page: https://better-flow.github.io/evimo/docs/ground-truth-format.html

Please let us know if you have any further questions! :)
