### ISSUE TITLE
About the depth map

### ISSUE THREAD

**Issue by ChannelG** [better-flow/evimo#14]
Hello, thanks for your great work. I'm about to do some research about motion segementation based on event camera. I have a question here, I see the depth maps are provided in EV-IMO Dataset, however, there's only depth info of moving objects but without background. I'm wondering how could I get the ground truth depth of the whole frame including the background. Thanks in advance.

**Comment by aftersomemath** [comment]
Hello thanks for your question. Low resolution depth is available in the background for the original EVIMO dataset. However, background depth is not available for the EVIMO2 dataset.

The website has been recently updated to make the difference more clear.

**Comment by rwn17** [comment]
> Hello thanks for your question. Low resolution depth is available in the background for the original EVIMO dataset. However, background depth is not available for the EVIMO2 dataset.
> 
> The website has been recently updated to make the difference more clear.

Thanks for your great work! I was wondering where can I find this "low-resolution depth for background"? I check the npz type file and raw rosbag and didn't find it. Thanks in advance!
