### ISSUE TITLE
assessment code

### ISSUE THREAD

**Issue by Carter-1998** [better-flow/evimo#17]
Thank you for your data set, I want to test my motion segmentation algorithm on this dataset. Could you provide an assessment code so that compares with Baseline?

**Comment by aftersomemath** [comment]
Sorry for the very late reply. Can you provide more details as to what assessment code is needed?

The ground truth segmentation masks per-pixel segmentation masks are provided in the dataset(s) as described [here](https://better-flow.github.io/evimo/docs/ground-truth-format.html). Calculating a simple per-pixel segmentation score with NumPy should be as simple as:

```python
score = np.sum(gt_mask == predicted_mask) / gt_mask.size()
```
