### ISSUE TITLE
Vicon installation guide

### ISSUE THREAD

**Issue by sam575** [better-flow/evimo#2]
Hello,
As the ground truth depth is not provided in the dataset, I am trying to run the generation pipeline on the raw data. But I am confused on how to configure and setup vicon. Can you please provide the steps for setting up vicon?

**Comment by ncos** [comment]
The ground truth for depth is not provided, but masks/vicon tracks are there! We use this package: https://github.com/KumarRobotics/vicon (only vicon messages are needed to build the code).

**Comment by sam575** [comment]
Thanks!
