### ISSUE TITLE
Camera Pose/Velocities for EVIMO1

### ISSUE THREAD

**Issue by ZiyunClaudeWang** [better-flow/evimo#24]
Hi, I have some questions regarding getting the camera velocities in the camera frame from the original EVIMO data. Currently, I'm using the `vel` field of the cameras under the `frames` key of the npz files. What frames are these velocities represented in? Also, are the camera poses in the same dictionary `T^{world}_cam` after converting them from quaternions?

My guess was the velocities were in the world frame and they needed to be converted to the camera frame by using the camera poses. I tried visualizing the velocities but they didn't seem to be consistent with the camera motions. Could you kindly point out what could have gone wrong?

**Comment by aftersomemath** [comment]
Hi. Unfortunately I have to recommend not using the velocities from EVIMO1. For one I was told it was "experimental". Second I noticed it probably wasn't being done right when preparing EVIMO2v2 and so I disabled it for EVIMO2v2. I dont remember the details but I came to that conclusion after reading the relevant codes.

Yes the pose of the camera is reported as T^w_c. The pose of objects are reported as T^c_o.

So, to get the velocity of the camera in the world frame you can numerically differentiate it's position using the method of your choice and rotate the vector into the camera frame if desired.
