### ISSUE TITLE
lens selection of event camera dvs346

### ISSUE THREAD

**Issue by louzq16** [better-flow/evimo#26]
Appreciate for your great work~

I have some questions about dvs346's lens' selection. 
Could you please tell which camera lens you select for capturing the sequence?

**Comment by aftersomemath** [comment]
Hi, I do not have information on the exact lens model used for EVIMO1. However, the intrinsics are available in the [NPZ](https://better-flow.github.io/evimo/docs/ground-truth-format.html#npz-evimo-and-evimo2v1) and [TXT](https://better-flow.github.io/evimo/docs/ground-truth-format.html#txt) formats as described in the documentation.
