### ISSUE TITLE
Regenerate higher frequency mask GT(>40hz) on EVIMO

### ISSUE THREAD

**Issue by doublemanyu** [better-flow/evimo#29]
Hi, there. Thanks for your sharing code of GT regeneration.
I have a question when I regenerate GT on EV-IMO (not EVIMO2). 
Is there a way for EV-IMO to regenrate GT in a higher frequency(> 40hz)?  Cause you said ground truth only generated when both events (or camera  frame) and Vicon pose are available. 
Please let me know whether it can regeneration higher frequency mask GT on EVIMO.
Thanks in advance if you can reply me as soon as possible.

**Comment by aftersomemath** [comment]
Hello,

Yes, you can regenerate higher framerate ground truth for the event cameras (for RGB cameras I believe the rate is fixed to the RGB cameras shutter speed).

Some documentation for the offline generation tool is available here: https://better-flow.github.io/evimo/docs/offline-generation-tool.html

See the documentation for the "fps" parameter for details.
