### ISSUE TITLE
where to find original image

### ISSUE THREAD

**Issue by Jee-King** [better-flow/evimo#3]
Thanks for your great datasets. I didn't find original gray images, it seems you only provide the splicing video.

**Comment by ncos** [comment]
The original images should be available if you use the .txt format ([https://better-flow.github.io/evimo/downloads.html](https://better-flow.github.io/evimo/downloads.html)), together with their timestamps.

**Comment by Jee-King** [comment]
OK, thank you!

**Comment by Jee-King** [comment]
Hi,  _depth_mask.png_ images are 48 bit. How can I get the mask information? I don't clear how you save  _depth_mask.png_ images.

**Comment by ncos** [comment]
Yes, this part is not that trivial: see code [here](https://github.com/better-flow/evimo/blob/efeab61147958bd3b64dc6354d5eb7db1bacce68/evimo/dataset_frame.h#L258). There are 3 channels {_depth, _depth, _mask}, and all are multiplied by 1000 and converted to int (so, depth is in integer mm.).

Just a heads up - this dataset is more about the masks than depth, and background depth might be not very accurate, although the objects should be good.

**Comment by Jee-King** [comment]
Thanks again. I will read your provided code.

**Comment by Jee-King** [comment]
Hi, thanks for your great datasets. I did not find the data you described below. In which data folder is it hidden?
         _background  speed   texture   occlusions  objects        light
Set 6  boxes           high     medium   low            1-3              dark / flicker_

**Comment by ncos** [comment]
Can you please clarify what you mean? :) If you refer to classes described in the paper, the released sets follow that roughly, but not word-to-word (we had to reorganize some stuff). We didn't use the dark/flicker sets in the paper and did not release these as far as I remember.

**Comment by Jee-King** [comment]
Thanks, I get it.
