### ISSUE TITLE
 Is there any way to remove the mask of non-moving objects?

### ISSUE THREAD

**Issue by ChenaoJIANG** [better-flow/evimo#30]
Hi, 
Thanks for your great work! 

I noticed that there are some objects that are not moving throughout the scene in the evimo2v2, and I'm dong work on segmenting moving objects, these non-moving masks in the groud truth are a distraction for me, so I'm wondering if there's an easy way to remove the masks of non-moving objects and only keep the masks of moving objects?

Thanks in advance if you can reply me as soon as possible.

**Comment by aftersomemath** [comment]
Hi,

There is not an easy way. But it should not be hard either. Each mask has an integer id. So you just need to make a list, per sequence, of the object id's that don't move.

You might be able to do this automatically, but you would need to chain a series of transformations to get the objects pose in the world frame, then check that it's velocity is under a threshold, then remove the associated masks. This also is also a medium level of difficulty.

Hope that helps.

**Comment by ChenaoJIANG** [comment]
Thanks for your fase reponse! It's very useful for me!

Could you explain how I can get the objects pose in world frame? I want to use the object pose(T^c_o) and the camera pose(T^w_c) in the meta.txt file, but I don't know much about quaternion, euler angles... So it would help me a lot if you could give me a clear example of the transformations.

Thanks again for your useful reply.

**Comment by aftersomemath** [comment]
In `evimo_flow.py` there is a function `get_all_poses` that extracts the poses from the meta file. The poses are actually the transforms T^c_o and T^w_c. See [here](https://github.com/better-flow/evimo/blob/aa1fcaa82613e1617051f268c4483ce807ba0ce9/tools/evimo_flow.py#L248).

You can then use the `apply_transform` function from `evimo_flow.py` to compose two transforms to get T^w_o. See [here](https://github.com/better-flow/evimo/blob/aa1fcaa82613e1617051f268c4483ce807ba0ce9/tools/evimo_flow.py#L158)

For example something like this should work for the time `t=0.5` (I didn't actually test this, but it should be close to correct):

```python
all_poses  = get_all_poses(meta)

t = 0.5
t_index_cam    = np.searchsorted(all_poses['cam']    [:, 0], t)
t_index_object = np.searchsorted(all_poses[object_id][:, 0], t)

T_wo = apply_transform(all_poses['cam']    [t_index_cam],
                       all_poses[object_id][t_index_object])
```

In `evimo_flow.py` there is also an `interpolate_pose` function which can help when the timestamp does not correspond to an integer index. See its definition [here](https://github.com/better-flow/evimo/blob/aa1fcaa82613e1617051f268c4483ce807ba0ce9/tools/evimo_flow.py#L126) and its usage [here](https://github.com/better-flow/evimo/blob/aa1fcaa82613e1617051f268c4483ce807ba0ce9/tools/evimo_flow.py#L538).

**Comment by ChenaoJIANG** [comment]
Thanks for your useful reply, I'm still a bit confused about the difference between `frame` and `full_trajectory` in the file 'meta'.

**Comment by aftersomemath** [comment]
full_trajectory is all the measurements collected from the motion capture system. The frame's report the pose at the time of frame generation. I generally just use full_trajectory.
