### ISSUE TITLE
extrinsics overlay details

### ISSUE THREAD

**Issue by Goulustis** [better-flow/evimo#31]
Thanks for the dataset!

I'm also trying to project rgb to events or the other way around. I see that extrinsic overlay is provided to align the cameras. However, I'm very confused as to how to apply it to the given extrinsics of each camera to align the cameras together. Any information will be of great help (eg. are they camera to vicon?). 

Thanks in advance!

**Comment by aftersomemath** [comment]
Hi!

Yes, if I remember correctly they are camera to vicon.

We provide a tool that can reproject the RGB image into an event camera's frame (up to occlusions and field of view overlap of course) using the depth information and intrinsics. See [here](https://better-flow.github.io/evimo/docs/evimo-flow.html)

Hope that helps!

**Comment by Goulustis** [comment]
Thanks!

I have found the math I'm looking for in the linked file. However the notation is quite confusing. I was wondering if you could give insight to what the T_* symbols from the two places below mean?

[here](https://github.com/better-flow/evimo/blob/6e2a483bd52d87d03056b6daf81418ed36ee0642/tools/evimo_flow.py#L378C1-L378C41)
`        T_gr = load_extrinsics(bgr_file)
         T_gc = load_extrinsics(file)
         T_cr = apply_transform(inv_transform(T_gc), T_gr)`

and [here](https://github.com/better-flow/evimo/blob/6e2a483bd52d87d03056b6daf81418ed36ee0642/tools/evimo_flow.py#L567)
`               T_c2o = interpolate_pose(bgr_frame_info['ts'], all_poses[key])
                T_c2c1 = apply_transform(T_c2o, inv_transform(T_c1o))
                T_r2c1 = apply_transform(inv_transform(T_cr), T_c2c1)`         

Thanks!

**Comment by aftersomemath** [comment]
It should be:
`T_gr` is rgb camera to camera rig.
`T_gc` is event camera to camera rig.
`T_cr` is rgb camera to event camera.
`T_c2o` is object to event camera frame at time 2 (in this case `bgr_frame_info['ts']`)
`T_c2c1` is event camera frame at time 1 to event camera frame at time 2.
`T_r2c1` is event camera frame at time 1 to rgb camera frame at time 2.

This last transform (plus the depth information in the event camera frame) allows an RGB image at one time to be reprojected into the event camera frame at another time. This makes it possible to render high fps RGB data in the event camera frame even though the RGB camera ran at lower rate.

I am not sure of your familiarity with coordinate frame conventions, but if you are wondering why the subscripts are written in the order they are you can check out the "subscript cancellation rule" explained on [page 91 of Modern Robotics](https://hades.mech.northwestern.edu/images/2/25/MR-v2.pdf) (pdf page 111).

**Comment by Goulustis** [comment]
I have solved my problem. Thanks for the help!
