### ISSUE TITLE
Training code and models

### ISSUE THREAD

**Issue by sam575** [better-flow/evimo#4]
Hello,
In the paper, it was mentioned that code and trained models will be made available. Will they be released?

**Comment by ncos** [comment]
We got a little sidetracked with other projects unfortunately; I hope I will find some time to bring the code to usable condition and release it in some time - but for now we only released the dataset (and, even the dataset Wiki is not done!). I think the results can be mostly replicated by using any SfMLearner-like NN (plenty released on GitHub), but I advise you check with [Chengxi](https://github.com/yechengxi), a co-author - he can provide a better insight.
