### ISSUE TITLE
How to ensure that the timestamps of vicon and event camera are aligned?

### ISSUE THREAD

**Issue by Jee-King** [better-flow/evimo#7]
Hi, 
How to ensure that the timestamps of Vicon and event camera are aligned?

**Comment by Gatsby23** [comment]
> For now, unfortunately, manually. The spatial calibration of the system should be done with static objects and camera - then any misalignment is due to time. In the generator app there is a manual slider which shifts the timestamps of mocap system, and the time offset (for a given recording) is written in the extrinsic calibration file.
> 
> It would be theoretically possible to correlate camera motion and event rate (without the need for spatial calibration), but that proved to be not accurate enough.

So, how to evaluate the camera pose between the gt truth？
